package config

import (
	"SirisakTour/entity"

	"gorm.io/driver/sqlite"
	"gorm.io/gorm"
)

func SetupDatabase() {
	db, err := gorm.Open(sqlite.Open("SirisakTour.db"), &gorm.Config{})
	if err != nil {
		panic("failed to connect to database")
	}

	db.AutoMigrate(&entity.Vehicles{}, &entity.BusTiming{}, &entity.Route{}, &entity.RouteData{},
		&entity.Employees{}, &entity.Drivers{}, entity.Member{}, &entity.Gender{}, &entity.Passenger{},
		&entity.Payment{}, &entity.TicketVerification{})
	var count int64
	db.Model(&entity.RouteData{}).Count(&count)
	if count == 0 {
		db.Create(&entity.RouteData{Province1: "นครราชสีมา", Province2: "บุรีรัมย์", Distance: 149, Time: 141})
		db.Create(&entity.RouteData{Province1: "นครราชสีมา", Province2: "สุรินทร์", Distance: 219, Time: 205})
		db.Create(&entity.RouteData{Province1: "นครราชสีมา", Province2: "ศรีสะเกษ", Distance: 300, Time: 276})
		db.Create(&entity.RouteData{Province1: "นครราชสีมา", Province2: "อุบลราชธานี", Distance: 354, Time: 305})
		db.Create(&entity.RouteData{Province1: "อุบลราชธานี", Province2: "ศรีสะเกษ", Distance: 88, Time: 82})
		db.Create(&entity.RouteData{Province1: "อุบลราชธานี", Province2: "สุรินทร์", Distance: 150, Time: 155})
		db.Create(&entity.RouteData{Province1: "อุบลราชธานี", Province2: "บุรีรัมย์", Distance: 279, Time: 231})
		db.Create(&entity.RouteData{Province1: "อุบลราชธานี", Province2: "นครราชสีมา", Distance: 354, Time: 305})
		db.Create(&entity.RouteData{Province1: "นครราชสีมา", Province2: "มหาสารคาม", Distance: 228, Time: 223})
		db.Create(&entity.RouteData{Province1: "นครราชสีมา", Province2: "ร้อยเอ็ด", Distance: 263, Time: 244})
		db.Create(&entity.RouteData{Province1: "นครราชสีมา", Province2: "ยโสธร", Distance: 359, Time: 332})
		db.Create(&entity.RouteData{Province1: "นครราชสีมา", Province2: "อำนาจเจริญ", Distance: 384, Time: 353})
		db.Create(&entity.RouteData{Province1: "นครราชสีมา", Province2: "มุกดาหาร", Distance: 400, Time: 375})
		db.Create(&entity.RouteData{Province1: "มุกดาหาร", Province2: "อำนาจเจริญ", Distance: 82, Time: 92})
		db.Create(&entity.RouteData{Province1: "มุกดาหาร", Province2: "ยโสธร", Distance: 60, Time: 72})
		db.Create(&entity.RouteData{Province1: "มุกดาหาร", Province2: "ร้อยเอ็ด", Distance: 157, Time: 164})
		db.Create(&entity.RouteData{Province1: "มุกดาหาร", Province2: "มหาสารคาม", Distance: 171, Time: 149})
		db.Create(&entity.RouteData{Province1: "มุกดาหาร", Province2: "นครราชสีมา", Distance: 400, Time: 375})
		db.Create(&entity.RouteData{Province1: "นครราชสีมา", Province2: "ขอนแก่น", Distance: 196, Time: 191})
		db.Create(&entity.RouteData{Province1: "นครราชสีมา", Province2: "กาฬสินธุ์", Distance: 287, Time: 270})
		db.Create(&entity.RouteData{Province1: "นครราชสีมา", Province2: "สกลนคร", Distance: 394, Time: 383})
		db.Create(&entity.RouteData{Province1: "นครราชสีมา", Province2: "นครพนม", Distance: 492, Time: 444})
		db.Create(&entity.RouteData{Province1: "นครพนม", Province2: "สกลนคร", Distance: 109, Time: 118})
		db.Create(&entity.RouteData{Province1: "นครพนม", Province2: "กาฬสินธุ์", Distance: 187, Time: 179})
		db.Create(&entity.RouteData{Province1: "นครพนม", Province2: "ขอนแก่น", Distance: 360, Time: 317})
		db.Create(&entity.RouteData{Province1: "นครพนม", Province2: "นครราชสีมา", Distance: 492, Time: 444})
		db.Create(&entity.RouteData{Province1: "นครราชสีมา", Province2: "ชัยภูมิ", Distance: 181, Time: 184})
		db.Create(&entity.RouteData{Province1: "นครราชสีมา", Province2: "เลย", Distance: 358, Time: 348})
		db.Create(&entity.RouteData{Province1: "นครราชสีมา", Province2: "หนองบัวลำภู", Distance: 325, Time: 323})
		db.Create(&entity.RouteData{Province1: "นครราชสีมา", Province2: "อุดรธานี", Distance: 328, Time: 313})
		db.Create(&entity.RouteData{Province1: "นครราชสีมา", Province2: "หนองคาย", Distance: 358, Time: 341})
		db.Create(&entity.RouteData{Province1: "หนองคาย", Province2: "อุดรธานี", Distance: 67, Time: 67})
		db.Create(&entity.RouteData{Province1: "หนองคาย", Province2: "หนองบัวลำภู", Distance: 159, Time: 164})
		db.Create(&entity.RouteData{Province1: "หนองคาย", Province2: "เลย", Distance: 187, Time: 214})
		db.Create(&entity.RouteData{Province1: "หนองคาย", Province2: "ชัยภูมิ", Distance: 254, Time: 249})
		db.Create(&entity.RouteData{Province1: "หนองคาย", Province2: "นครราชสีมา", Distance: 358, Time: 341})
		db.Create(&entity.RouteData{Province1: "นครราชสีมา", Province2: "สระบุรี", Distance: 181, Time: 172})
		db.Create(&entity.RouteData{Province1: "นครราชสีมา", Province2: "ปทุมธานี", Distance: 259, Time: 223})
		db.Create(&entity.RouteData{Province1: "นครราชสีมา", Province2: "กรุงเทพมหานคร", Distance: 292, Time: 244})
		db.Create(&entity.RouteData{Province1: "กรุงเทพมหานคร", Province2: "ปทุมธานี", Distance: 43, Time: 52})
		db.Create(&entity.RouteData{Province1: "กรุงเทพมหานคร", Province2: "สระบุรี", Distance: 112, Time: 91})
		db.Create(&entity.RouteData{Province1: "กรุงเทพมหานคร", Province2: "นครราชสีมา", Distance: 292, Time: 244})
		db.Create(&entity.RouteData{Province1: "กรุงเทพมหานคร", Province2: "ชลบุรี", Distance: 123, Time: 138})
		db.Create(&entity.RouteData{Province1: "กรุงเทพมหานคร", Province2: "ระยอง", Distance: 191, Time: 168})
		db.Create(&entity.RouteData{Province1: "กรุงเทพมหานคร", Province2: "จันทบุรี", Distance: 300, Time: 278})
		db.Create(&entity.RouteData{Province1: "กรุงเทพมหานคร", Province2: "ตราด", Distance: 374, Time: 347})
		db.Create(&entity.RouteData{Province1: "ตราด", Province2: "จันทบุรี", Distance: 74, Time: 68})
		db.Create(&entity.RouteData{Province1: "ตราด", Province2: "ระยอง", Distance: 176, Time: 164})
		db.Create(&entity.RouteData{Province1: "ตราด", Province2: "ชลบุรี", Distance: 204, Time: 179})
		db.Create(&entity.RouteData{Province1: "ตราด", Province2: "กรุงเทพมหานคร", Distance: 374, Time: 347})
		db.Create(&entity.RouteData{Province1: "กรุงเทพมหานคร", Province2: "นนทบุรี", Distance: 30, Time: 37})
		db.Create(&entity.RouteData{Province1: "กรุงเทพมหานคร", Province2: "พระนครศรีอยุธยา", Distance: 74, Time: 63})
		db.Create(&entity.RouteData{Province1: "กรุงเทพมหานคร", Province2: "อ่างทอง", Distance: 118, Time: 107})
		db.Create(&entity.RouteData{Province1: "กรุงเทพมหานคร", Province2: "สิงห์บุรี", Distance: 150, Time: 133})
		db.Create(&entity.RouteData{Province1: "กรุงเทพมหานคร", Province2: "นครสวรรค์", Distance: 238, Time: 193})
		db.Create(&entity.RouteData{Province1: "กรุงเทพมหานคร", Province2: "พิษณุโลก", Distance: 377, Time: 305})
		db.Create(&entity.RouteData{Province1: "กรุงเทพมหานคร", Province2: "อุตรดิตถ์", Distance: 523, Time: 427})
		db.Create(&entity.RouteData{Province1: "กรุงเทพมหานคร", Province2: "แพร่", Distance: 569, Time: 467})
		db.Create(&entity.RouteData{Province1: "กรุงเทพมหานคร", Province2: "น่าน", Distance: 665, Time: 556})
		db.Create(&entity.RouteData{Province1: "น่าน", Province2: "แพร่", Distance: 103, Time: 104})
		db.Create(&entity.RouteData{Province1: "น่าน", Province2: "อุตรดิตถ์", Distance: 237, Time: 222})
		db.Create(&entity.RouteData{Province1: "น่าน", Province2: "พิษณุโลก", Distance: 290, Time: 258})
		db.Create(&entity.RouteData{Province1: "น่าน", Province2: "นครสวรรค์", Distance: 424, Time: 365})
		db.Create(&entity.RouteData{Province1: "น่าน", Province2: "สิงห์บุรี", Distance: 521, Time: 441})
		db.Create(&entity.RouteData{Province1: "น่าน", Province2: "อ่างทอง", Distance: 559, Time: 471})
		db.Create(&entity.RouteData{Province1: "น่าน", Province2: "พระนครศรีอยุธยา", Distance: 595, Time: 494})
		db.Create(&entity.RouteData{Province1: "น่าน", Province2: "นนทบุรี", Distance: 650, Time: 549})
		db.Create(&entity.RouteData{Province1: "น่าน", Province2: "กรุงเทพมหานคร", Distance: 665, Time: 556})
		db.Create(&entity.RouteData{Province1: "กรุงเทพมหานคร", Province2: "นนทบุรี", Distance: 30, Time: 36})
		db.Create(&entity.RouteData{Province1: "กรุงเทพมหานคร", Province2: "พระนครศรีอยุธยา", Distance: 74, Time: 64})
		db.Create(&entity.RouteData{Province1: "กรุงเทพมหานคร", Province2: "อ่างทอง", Distance: 118, Time: 107})
		db.Create(&entity.RouteData{Province1: "กรุงเทพมหานคร", Province2: "สิงห์บุรี", Distance: 150, Time: 134})
		db.Create(&entity.RouteData{Province1: "กรุงเทพมหานคร", Province2: "นครสวรรค์", Distance: 238, Time: 193})
		db.Create(&entity.RouteData{Province1: "กรุงเทพมหานคร", Province2: "พิษณุโลก", Distance: 377, Time: 305})
		db.Create(&entity.RouteData{Province1: "กรุงเทพมหานคร", Province2: "อุตรดิตถ์", Distance: 523, Time: 424})
		db.Create(&entity.RouteData{Province1: "กรุงเทพมหานคร", Province2: "แพร่", Distance: 569, Time: 464})
		db.Create(&entity.RouteData{Province1: "กรุงเทพมหานคร", Province2: "พะเยา", Distance: 698, Time: 576})
		db.Create(&entity.RouteData{Province1: "กรุงเทพมหานคร", Province2: "เชียงราย", Distance: 789, Time: 664})
		db.Create(&entity.RouteData{Province1: "เชียงราย", Province2: "พะเยา", Distance: 91, Time: 87})
		db.Create(&entity.RouteData{Province1: "เชียงราย", Province2: "แพร่", Distance: 216, Time: 209})
		db.Create(&entity.RouteData{Province1: "เชียงราย", Province2: "อุตรดิตถ์", Distance: 361, Time: 341})
		db.Create(&entity.RouteData{Province1: "เชียงราย", Province2: "พิษณุโลก", Distance: 413, Time: 371})
		db.Create(&entity.RouteData{Province1: "เชียงราย", Province2: "นครสวรรค์", Distance: 545, Time: 485})
		db.Create(&entity.RouteData{Province1: "เชียงราย", Province2: "สิงห์บุรี", Distance: 645, Time: 559})
		db.Create(&entity.RouteData{Province1: "เชียงราย", Province2: "อ่างทอง", Distance: 685, Time: 580})
		db.Create(&entity.RouteData{Province1: "เชียงราย", Province2: "พระนครศรีอยุธยา", Distance: 714, Time: 609})
		db.Create(&entity.RouteData{Province1: "เชียงราย", Province2: "นนทบุรี", Distance: 781, Time: 654})
		db.Create(&entity.RouteData{Province1: "เชียงราย", Province2: "กรุงเทพมหานคร", Distance: 789, Time: 664})
		db.Create(&entity.RouteData{Province1: "กรุงเทพมหานคร", Province2: "นนทบุรี", Distance: 30, Time: 38})
		db.Create(&entity.RouteData{Province1: "กรุงเทพมหานคร", Province2: "พระนครศรีอยุธยา", Distance: 74, Time: 63})
		db.Create(&entity.RouteData{Province1: "กรุงเทพมหานคร", Province2: "อ่างทอง", Distance: 118, Time: 106})
		db.Create(&entity.RouteData{Province1: "กรุงเทพมหานคร", Province2: "สิงห์บุรี", Distance: 150, Time: 132})
		db.Create(&entity.RouteData{Province1: "กรุงเทพมหานคร", Province2: "นครสวรรค์", Distance: 238, Time: 192})
		db.Create(&entity.RouteData{Province1: "กรุงเทพมหานคร", Province2: "ตาก", Distance: 433, Time: 353})
		db.Create(&entity.RouteData{Province1: "กรุงเทพมหานคร", Province2: "ลำปาง", Distance: 677, Time: 570})
		db.Create(&entity.RouteData{Province1: "กรุงเทพมหานคร", Province2: "ลำพูน", Distance: 605, Time: 508})
		db.Create(&entity.RouteData{Province1: "กรุงเทพมหานคร", Province2: "เชียงใหม่", Distance: 687, Time: 555})
		db.Create(&entity.RouteData{Province1: "เชียงใหม่", Province2: "ลำพูน", Distance: 107, Time: 114})
		db.Create(&entity.RouteData{Province1: "เชียงใหม่", Province2: "ลำปาง", Distance: 121, Time: 179})
		db.Create(&entity.RouteData{Province1: "เชียงใหม่", Province2: "ตาก", Distance: 274, Time: 239})
		db.Create(&entity.RouteData{Province1: "เชียงใหม่", Province2: "นครสวรรค์", Distance: 453, Time: 378})
		db.Create(&entity.RouteData{Province1: "เชียงใหม่", Province2: "สิงห์บุรี", Distance: 549, Time: 462})
		db.Create(&entity.RouteData{Province1: "เชียงใหม่", Province2: "อ่างทอง", Distance: 581, Time: 484})
		db.Create(&entity.RouteData{Province1: "เชียงใหม่", Province2: "พระนครศรีอยุธยา", Distance: 617, Time: 500})
		db.Create(&entity.RouteData{Province1: "เชียงใหม่", Province2: "นนทบุรี", Distance: 672, Time: 544})
		db.Create(&entity.RouteData{Province1: "เชียงใหม่", Province2: "กรุงเทพมหานคร", Distance: 687, Time: 555})
		db.Create(&entity.RouteData{Province1: "กรุงเทพมหานคร", Province2: "สมุทรสาคร", Distance: 56, Time: 62})
		db.Create(&entity.RouteData{Province1: "กรุงเทพมหานคร", Province2: "สมุทรสงคราม", Distance: 91, Time: 82})
		db.Create(&entity.RouteData{Province1: "กรุงเทพมหานคร", Province2: "เพชรบุรี", Distance: 176, Time: 149})
		db.Create(&entity.RouteData{Province1: "กรุงเทพมหานคร", Province2: "ประจวบคีรีขันธ์", Distance: 253, Time: 213})
		db.Create(&entity.RouteData{Province1: "กรุงเทพมหานคร", Province2: "ชุมพร", Distance: 461, Time: 367})
		db.Create(&entity.RouteData{Province1: "กรุงเทพมหานคร", Province2: "ระนอง", Distance: 578, Time: 472})
		db.Create(&entity.RouteData{Province1: "กรุงเทพมหานคร", Province2: "พังงา", Distance: 765, Time: 648})
		db.Create(&entity.RouteData{Province1: "กรุงเทพมหานคร", Province2: "กระบี่", Distance: 784, Time: 647})
		db.Create(&entity.RouteData{Province1: "กรุงเทพมหานคร", Province2: "ตรัง", Distance: 838, Time: 684})
		db.Create(&entity.RouteData{Province1: "กรุงเทพมหานคร", Province2: "สตูล", Distance: 951, Time: 795})
		db.Create(&entity.RouteData{Province1: "สตูล", Province2: "ตรัง", Distance: 120, Time: 116})
		db.Create(&entity.RouteData{Province1: "สตูล", Province2: "กระบี่", Distance: 226, Time: 207})
		db.Create(&entity.RouteData{Province1: "สตูล", Province2: "พังงา", Distance: 352, Time: 327})
		db.Create(&entity.RouteData{Province1: "สตูล", Province2: "ระนอง", Distance: 518, Time: 470})
		db.Create(&entity.RouteData{Province1: "สตูล", Province2: "ชุมพร", Distance: 516, Time: 437})
		db.Create(&entity.RouteData{Province1: "สตูล", Province2: "ประจวบคีรีขันธ์", Distance: 714, Time: 620})
		db.Create(&entity.RouteData{Province1: "สตูล", Province2: "เพชรบุรี", Distance: 813, Time: 703})
		db.Create(&entity.RouteData{Province1: "สตูล", Province2: "สมุทรสงคราม", Distance: 850, Time: 720})
		db.Create(&entity.RouteData{Province1: "สตูล", Province2: "สมุทรสาคร", Distance: 920, Time: 780})
		db.Create(&entity.RouteData{Province1: "สตูล", Province2: "กรุงเทพมหานคร", Distance: 951, Time: 795})
		db.Create(&entity.RouteData{Province1: "กรุงเทพมหานคร", Province2: "สมุทรสาคร", Distance: 56, Time: 64})
		db.Create(&entity.RouteData{Province1: "กรุงเทพมหานคร", Province2: "สมุทรสงคราม", Distance: 91, Time: 85})
		db.Create(&entity.RouteData{Province1: "กรุงเทพมหานคร", Province2: "เพชรบุรี", Distance: 176, Time: 151})
		db.Create(&entity.RouteData{Province1: "กรุงเทพมหานคร", Province2: "ประจวบคีรีขันธ์", Distance: 253, Time: 215})
		db.Create(&entity.RouteData{Province1: "กรุงเทพมหานคร", Province2: "ชุมพร", Distance: 461, Time: 371})
		db.Create(&entity.RouteData{Province1: "กรุงเทพมหานคร", Province2: "สุราษฎร์ธานี", Distance: 670, Time: 553})
		db.Create(&entity.RouteData{Province1: "กรุงเทพมหานคร", Province2: "นครศรีธรรมราช", Distance: 744, Time: 629})
		db.Create(&entity.RouteData{Province1: "กรุงเทพมหานคร", Province2: "พัทลุง", Distance: 857, Time: 699})
		db.Create(&entity.RouteData{Province1: "กรุงเทพมหานคร", Province2: "สงขลา", Distance: 968, Time: 799})
		db.Create(&entity.RouteData{Province1: "กรุงเทพมหานคร", Province2: "ปัตตานี", Distance: 1086, Time: 898})
		db.Create(&entity.RouteData{Province1: "กรุงเทพมหานคร", Province2: "นราธิวาส", Distance: 1169, Time: 956})
		db.Create(&entity.RouteData{Province1: "นราธิวาส", Province2: "ปัตตานี", Distance: 102, Time: 110})
		db.Create(&entity.RouteData{Province1: "นราธิวาส", Province2: "สงขลา", Distance: 232, Time: 210})
		db.Create(&entity.RouteData{Province1: "นราธิวาส", Province2: "พัทลุง", Distance: 329, Time: 282})
		db.Create(&entity.RouteData{Province1: "นราธิวาส", Province2: "นครศรีธรรมราช", Distance: 466, Time: 398})
		db.Create(&entity.RouteData{Province1: "นราธิวาส", Province2: "สุราษฎร์ธานี", Distance: 545, Time: 476})
		db.Create(&entity.RouteData{Province1: "นราธิวาส", Province2: "ชุมพร", Distance: 714, Time: 626})
		db.Create(&entity.RouteData{Province1: "นราธิวาส", Province2: "ประจวบคีรีขันธ์", Distance: 928, Time: 790})
		db.Create(&entity.RouteData{Province1: "นราธิวาส", Province2: "เพชรบุรี", Distance: 1030, Time: 868})
		db.Create(&entity.RouteData{Province1: "นราธิวาส", Province2: "สมุทรสงคราม", Distance: 1086, Time: 894})
		db.Create(&entity.RouteData{Province1: "นราธิวาส", Province2: "สมุทรสาคร", Distance: 1123, Time: 922})
		db.Create(&entity.RouteData{Province1: "นราธิวาส", Province2: "กรุงเทพมหานคร", Distance: 1169, Time: 956})

		db.Create(&entity.Route{NameRoute: "นครราชสีมา-อุบลราชธานี", Routeway: "นครราชสีมา-บุรีรัมย์-สุรินทร์-ศรีสะเกษ-อุบลราชธานี"})
		db.Create(&entity.Route{NameRoute: "อุบลราชธานี-นครราชสีมา", Routeway: "อุบลราชธานี-ศรีสะเกษ-สุรินทร์-บุรีรัมย์-นครราชสีมา"})
		db.Create(&entity.Route{NameRoute: "นครราชสีมา-มุกดาหาร", Routeway: "นครราชสีมา-มหาสารคาม-ร้อยเอ็ด-ยโสธร-อำนาจเจริญ-มุกดาหาร"})
		db.Create(&entity.Route{NameRoute: "มุกดาหาร-นครราชสีมา", Routeway: "มุกดาหาร-อำนาจเจริญ-ยโสธร-ร้อยเอ็ด-มหาสารคาม-นครราชสีมา"})
		db.Create(&entity.Route{NameRoute: "นครราชสีมา-นครพนม", Routeway: "นครราชสีมา-ขอนแก่น-กาฬสินธุ์-สกลนคร-นครพนม"})
		db.Create(&entity.Route{NameRoute: "นครพนม-นครราชสีมา", Routeway: "นครพนม-สกลนคร-กาฬสินธุ์-ขอนแก่น-นครราชสีมา"})
		db.Create(&entity.Route{NameRoute: "นครราชสีมา-หนองคาย", Routeway: "นครราชสีมา-ชัยภูมิ-เลย-หนองบัวลำภู-อุดรธานี-หนองคาย"})
		db.Create(&entity.Route{NameRoute: "หนองคาย-นครราชสีมา", Routeway: "หนองคาย-อุดรธานี-หนองบัวลำภู-เลย-ชัยภูมิ-นครราชสีมา"})
		db.Create(&entity.Route{NameRoute: "นครราชสีมา-กรุงเทพมหานคร", Routeway: "นครราชสีมา-สระบุรี-ปทุมธานี-กรุงเทพมหานคร"})
		db.Create(&entity.Route{NameRoute: "กรุงเทพมหานคร-นครราชสีมา", Routeway: "กรุงเทพมหานคร-ปทุมธานี-สระบุรี-นครราชสีมา"})
		db.Create(&entity.Route{NameRoute: "กรุงเทพมหานคร-ตราด", Routeway: "กรุงเทพมหานคร-ชลบุรี-ระยอง-จันทบุรี-ตราด"})
		db.Create(&entity.Route{NameRoute: "ตราด-กรุงเทพมหานคร", Routeway: "ตราด-จันทบุรี-ระยอง-ชลบุรี-กรุงเทพมหานคร"})
		db.Create(&entity.Route{NameRoute: "กรุงเทพมหานคร-น่าน", Routeway: "กรุงเทพมหานคร-นนทบุรี-พระนครศรีอยุธยา-อ่างทอง-สิงห์บุรี-นครสวรรค์-พิษณุโลก-อุตรดิตถ์-แพร่-น่าน"})
		db.Create(&entity.Route{NameRoute: "น่าน-กรุงเทพมหานคร", Routeway: "น่าน-แพร่-อุตรดิตถ์-พิษณุโลก-นครสวรรค์-สิงห์บุรี-อ่างทอง-พระนครศรีอยุธยา-นนทบุรี-กรุงเทพมหานคร"})
		db.Create(&entity.Route{NameRoute: "กรุงเทพมหานคร-เชียงราย", Routeway: "กรุงเทพมหานคร-นนทบุรี-พระนครศรีอยุธยา-อ่างทอง-สิงห์บุรี-นครสวรรค์-พิษณุโลก-อุตรดิตถ์-แพร่-พะเยา-เชียงราย"})
		db.Create(&entity.Route{NameRoute: "เชียงราย-กรุงเทพมหานคร", Routeway: "เชียงราย-พะเยา-แพร่-อุตรดิตถ์-พิษณุโลก-นครสวรรค์-สิงห์บุรี-อ่างทอง-พระนครศรีอยุธยา-นนทบุรี-กรุงเทพมหานคร"})
		db.Create(&entity.Route{NameRoute: "กรุงเทพมหานคร-เชียงใหม่", Routeway: "กรุงเทพมหานคร-นนทบุรี-พระนครศรีอยุธยา-อ่างทอง-สิงห์บุรี-นครสวรรค์-ตาก-ลำปาง-ลำพูน-เชียงใหม่"})
		db.Create(&entity.Route{NameRoute: "เชียงใหม่-กรุงเทพมหานคร", Routeway: "เชียงใหม่-ลำพูน-ลำปาง-ตาก-นครสวรรค์-สิงห์บุรี-อ่างทอง-พระนครศรีอยุธยา-นนทบุรี-กรุงเทพมหานคร"})
		db.Create(&entity.Route{NameRoute: "กรุงเทพมหานคร-สตูล", Routeway: "กรุงเทพมหานคร-สมุทรสาคร-สมุทรสงคราม-เพชรบุรี-ประจวบคีรีขันธ์-ชุมพร-ระนอง-พังงา-กระบี่-ตรัง-สตูล"})
		db.Create(&entity.Route{NameRoute: "สตูล-กรุงเทพมหานคร", Routeway: "สตูล-ตรัง-กระบี่-พังงา-ระนอง-ชุมพร-ประจวบคีรีขันธ์-เพชรบุรี-สมุทรสงคราม-สมุทรสาคร-กรุงเทพมหานคร"})
		db.Create(&entity.Route{NameRoute: "กรุงเทพมหานคร-นราธิวาส", Routeway: "กรุงเทพมหานคร-สมุทรสาคร-สมุทรสงคราม-เพชรบุรี-ประจวบคีรีขันธ์-ชุมพร-สุราษฎร์ธานี-นครศรีธรรมราช-พัทลุง-สงขลา-ปัตตานี-นราธิวาส"})
		db.Create(&entity.Route{NameRoute: "นราธิวาส-กรุงเทพมหานคร", Routeway: "นราธิวาส-ปัตตานี-สงขลา-พัทลุง-นครศรีธรรมราช-สุราษฎร์ธานี-ชุมพร-ประจวบคีรีขันธ์-เพชรบุรี-สมุทรสงคราม-สมุทรสาคร-กรุงเทพมหานคร"})

		member := entity.Member{Username: "user", Password: "123", Email: "User@gmail.com", FirstName: "GodPalm", LastName: "Chayapat", Birthday: "01-01-2001"}
		db.FirstOrCreate(&member)

		db.Create(&entity.Employees{Username: "admin", Password: "123", FirstName: "DEW", LastName: "Sirisak", PhoneNumber: "0965455214", Position: "Admin", Address: "บ้านหนองสาหร่าย", GenderID: 1})
		db.Create(&entity.Employees{Username: "driver", Password: "123", FirstName: "OHM", LastName: "Warawut", PhoneNumber: "0802544578", Position: "Driver", Address: "ดาวคะนอง", GenderID: 2})

		db.FirstOrCreate(&entity.Vehicles{Type: "Bus", BusRegistration: "สพ-568", Brand: "toyota", Series: "korea", Year: 2003, EngineAndPower: "V18-nismo", FuelTank: 5000, Seat: 50})
		db.FirstOrCreate(&entity.Drivers{EmployeeID: 2, BusID: 1})

		GenderMale := entity.Gender{Name: "Male"}
		GenderFemale := entity.Gender{Name: "Female"}

		db.FirstOrCreate(&GenderMale, &entity.Gender{Name: "Male"})
		db.FirstOrCreate(&GenderFemale, &entity.Gender{Name: "Female"})
	}
}
